version: '3.8'

services:
  flask-app:
    build: .
#    image: us-central1-docker.pkg.dev/suni1994/nginx/flask:latest
    image: us-central1-docker.pkg.dev/suni1994/nginx/flask:latest
    container_name: flask_app
    ports:
      - "5000:5000"
  
  nginx:
    image: nginx:latest

    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
 # image: us-central1-docker.pkg.dev/suni1994/nginx/flask:latest   
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - flask-app

